version: '3.8'
services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: googleApi
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - database
    ports:
      - 8080:8080
    networks:
      - dev
volumes:
  database_data:
networks:
  dev: